apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-prometheus-datasource
  namespace: monitoring
  labels:
     grafana_datasource: "1"
data:
  datasource.yaml: |-
    datasources:
    - name: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-server
